// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bHWw6dz8J6f3Uy4L-HiyviQzZ0vckZc',
    appId: '1:900355893748:web:c52607d718e75928cf71a1',
    messagingSenderId: '900355893748',
    projectId: 'johar-basket',
    authDomain: 'johar-basket.firebaseapp.com',
    storageBucket: 'johar-basket.appspot.com',
    measurementId: 'G-0M7ZLPZ8ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxJL9FezfsEQMisUZXorhbLl00N2xuXag',
    appId: '1:900355893748:android:68441b4fe8292112cf71a1',
    messagingSenderId: '900355893748',
    projectId: 'johar-basket',
    storageBucket: 'johar-basket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA3jAJnkSD0gNbkNV2GQJIYo08A5vBerU',
    appId: '1:900355893748:ios:18ca0b884e3c919ccf71a1',
    messagingSenderId: '900355893748',
    projectId: 'johar-basket',
    storageBucket: 'johar-basket.appspot.com',
    iosClientId: '900355893748-n6gqvl9h1bq5dkm5b7renbspgfv3la3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.johar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA3jAJnkSD0gNbkNV2GQJIYo08A5vBerU',
    appId: '1:900355893748:ios:1b80affa615b89decf71a1',
    messagingSenderId: '900355893748',
    projectId: 'johar-basket',
    storageBucket: 'johar-basket.appspot.com',
    iosClientId: '900355893748-k9g9rm1hp23qtjbsav28vm0bthb7tcqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.johar.RunnerTests',
  );
}
